In [ ]:
import numpy as np


In [ ]:
matrix1=np.array([[1,2,3],[2,3,4 ],[5,6,7]])
matrix2=np.array([[1,2,3],[2,3,4],[5,6,7]])
result_matrix=matrix1 + matrix2



In [4]:
!pip install numpy

In [34]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

a=np.zeros((3,3))
print(a)

a=np.ones((3,3))
print(a)

a=np.zeros((3,3),int)
print(a)

arange_arr=np.arange(10)
print(arange_arr)

#array manupulation
arr=np.array([1,2,3,4,5])
reshape_arr=arr.reshape(5,1)
print(reshape_arr)

slicedarr=arr[2:4]
print(slicedarr)

arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.vstack(arr1+arr2)
print(c)


arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
c=np.stack(arr1+arr2)
print(c)

arr1=np.array([1,2,3,4])
c=np.split(arr1,2)
print(c)







#mathmatical applications
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
arr= arr1+arr2
print(arr)
print(arr2+3)

#transpose path of array
import numpy as np
a=np.matrix([[1,2,3,4],[5,6,7,8]])
b=a.T
print(b)

#linear algebra with numpy

import numpy as np
arr1=np.matrix([[1,2],[3,4]])
arr2=np.matrix([[1,1],[2,2]])
c=np.dot(arr1,arr2)
print(c)

#calculating eigen values or eigen vector
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,1],[2,2]])
c=np.dot(arr1,arr2)
d=np.linalg.eig(c)
print(d)



[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[0 1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[[ 4]
 [ 6]
 [ 8]
 [10]]
[ 4  6  8 10]
[array([1, 2]), array([3, 4])]
[ 4  6  8 10]
[6 7 8 9]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[ 5  5]
 [11 11]]
(array([ 0., 16.]), array([[-0.70710678, -0.41380294],
       [ 0.70710678, -0.91036648]]))
